spring.application.name=catalog
spring.datasource.url=jdbc:postgresql://localhost:5432/freshdb
spring.jpa.properties.hibernate.default_schema=catalog
spring.datasource.username=catalog_user
spring.datasource.password=cataloguser13
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate